### ISSUE TITLE
Does LAEP_Hand support torque control?

### ISSUE THREAD

**Issue by RyanJiao** [leap-hand/LEAP_Hand_API#1]
I'd like to ask if i'm able to control the output torque of each joint, or have you ever tried the accurancy of torque control. I notice that DYNAMIXEL XC330-M288-T support current-based position control and current control mode.
Is it possible to use model-based control algorithem on LEAP_Hand?

[https://emanual.robotis.com/docs/en/dxl/x/xc330-m288/](url)
![$J`G}Y6Z(XK97RX18TY%C8Q](https://github.com/leap-hand/LEAP_Hand_API/assets/56286149/04343770-cf3e-4282-9b96-053a4659c647)

**Comment by Lucky7Chess** [comment]
Hi Ryan,

Yes, while there are no dedicated torque sensors at the joint, the current readings are approximately related to torque.  Please see the photo below.

![image](https://github.com/leap-hand/LEAP_Hand_API/assets/10481433/7278fd18-b0d5-4533-b39e-766928f1dfc2)

You can use current-control mode to set the torque directly.  Or you can use current-based position control mode to control the position and then secondarily the max torque that the motor will apply.   Finally, PWM is setting the output voltage of the motor directly, and it can also be used as a way to control the force of the motor if you would like.  

I will add this to the API, but it's also straightforward to implement yourself.

**Comment by RyanJiao** [comment]
Hi Kenny,


Thank you for your throughout reply and this wonderful open-source. I find the photo but highly doubt the accuracy while doing a torque control. I will implement it as soon as I get those motors.&nbsp;
Moreover, I’d like to ask if there is going to be any community to talk about the problems during implementing this project or to enrich further researches on this project like simulation and control?
Again thank you for your great work!



发自我的iPhone


------------------ Original ------------------
From: Kenny Shaw ***@***.***&gt;
Date: Mon,Oct 23,2023 1:30 AM
To: leap-hand/LEAP_Hand_API ***@***.***&gt;
Cc: Ryan Jiao ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [leap-hand/LEAP_Hand_API] Does LAEP_Hand support torque control?(Issue #1)





 
Hi Ryan,
 
Yes, while there are no dedicated torque sensors at the joint, the current readings are approximately related to torque.  Please see the photo below.
 

 
You can use current-control mode to set the torque directly.  Or you can use current-based position control mode to control the position and then secondarily the max torque that the motor will apply.   Finally, PWM is setting the output voltage of the motor directly, and it can also be used as a way to control the force of the motor if you would like.
 
I will add this to the API, but it's also straightforward to implement yourself.

**Comment by Lucky7Chess** [comment]
Hi Ryan,

Yes I am honestly not sure of the accuracy for Torque control.  When we were doing sim2real, we were actually using the error between the commanded and actual angle values of the motors as the proprioception for the sim policy to be able to feel the cube.  If the error is larger on the PID controller, then the motors are probably trying to push harder etc.

A community sounds like a good idea, we have had an overwhelming positive response to LEAP Hand.   We will be at CoRL and will try to meet many people there.  Maybe we can kickstart some sort of online community also.....
