### ISSUE TITLE
link for leaphand and franka emika

### ISSUE THREAD

**Issue by vincentkeino** [leap-hand/LEAP_Hand_API#10]
Hi，please help me. I want to link real leaphand and franka emika, could you tell me how you made the connection? Is it through a hole in the back of the hand or is a separate connector needed? Do you have any specific STL files that I could reference? Thank you for help!

**Comment by Lucky7Chess** [comment]
https://leaphand.com/leap_cad Please check our website for mounting plate for Franka thanks.

**Comment by vincentkeino** [comment]
oh！nice！I did not check it seriously on website，thank u！While link them togather and calculate xyz translation for emika end and leaphand in real world， i can use the translation to build simulation for them accurately， right？ thanks for ur answer！

**Comment by Lucky7Chess** [comment]
I don't understand exactly the problem.  This is not a GitHub issue though I believe.
