### ISSUE TITLE
Motor Delays and Failure to Reach Target Positions

### ISSUE THREAD

**Issue by kingchou007** [leap-hand/LEAP_Hand_API#11]
Hi,

I hope you are doing well. I am currently experiencing issues with the Leap Hand controller and would appreciate your guidance on addressing the following problems:

1. Motor Delays: When sending control commands to the hand, certain motors exhibit delays in reaching the target positions.
2. Inconsistent Target Positions: Some motors fail to achieve the intended target positions entirely.

My current control rate is 30hz.

 Could you please suggest potential solutions or troubleshooting steps to resolve this?

**Comment by Lucky7Chess** [comment]
You may have a buggy motor cable, or u2d2, or u2d2 driver or one bad motor.  I'd actually encourage you to try these but also reach out to robotis directly as they can warranty the parts for you and debug further.
