### ISSUE TITLE
reading additional dynamixel data and scaling factors 

### ISSUE THREAD

**Issue by zahid990170** [leap-hand/LEAP_Hand_API#12]
Hello, 

In the provided `dynamixel_client.py` there are addresses and data byte lengths which are obtained from the official protocol documentation for dynamixel. Then, there are scale factors, 
such as 

```
DEFAULT_POS_SCALE = 2.0 * np.pi / 4096  # 0.088 degrees
DEFAULT_VEL_SCALE = 0.229 * 2.0 * np.pi / 60.0  # 0.229 rpm
DEFAULT_CUR_SCALE = 1.34
```
How do we choose this scale. There are some other information such as moving status ( address 123), which would not need a scaling ? I am trying to follow the conventions in `dynamixel_client.py` and read additional information such as status of movement or another data. 

thanks,

**Comment by Lucky7Chess** [comment]
This is from the Dynamixel API directly.  I did not create these scaling.
