### ISSUE TITLE
ros2_module error

### ISSUE THREAD

**Issue by Yon9-Jun** [leap-hand/LEAP_Hand_API#13]
Thank you so much for uploading the new ros2_module. 
When I followed the readme and ran it, an error like [ModuleNotFoundError: No module named 'rclpy._rclpy_pybind11'] appeared. I wonder if this is an error I have seen in the process of developing a new package.
I thought I needed python3.12 to use ros2_module, so I installed and ran that version of python. Is there a problem with the python version?

**Comment by Lucky7Chess** [comment]
I was using ros2 humble on Python 3.10 on Ubuntu 22.  Not sure if it's some sort of ros2 difference.
