### ISSUE TITLE
ROS1 module mistake

### ISSUE THREAD

**Issue by Seize-Future** [leap-hand/LEAP_Hand_API#15]
Hello, I may find some mistakes in the code of ros_module package. The leaphand_node.py in the ros_module folder seens to be ros2 version, which is unable to execute.
Hopefully if there is any revision for this issue, thank you.

**Comment by Lucky7Chess** [comment]
Sorry, I fixed this.  Not many people use the ROS1 library so I haven't been keeping up on it.  Can you check and let me know if everything works okay for you?

**Comment by Seize-Future** [comment]
As the sim2real repository utilizes ROS1 library, so this update is important for me. Thanks for your generous help, it works well now!

**Comment by Lucky7Chess** [comment]
Ah yes......I forgot about that.  Now that Isaac Gym and ROS1 are deprecated I suppose that codebase is legacy but still useful!
