### ISSUE TITLE
LEAP hand and tactile sensors?

### ISSUE THREAD

**Issue by cemoke** [leap-hand/LEAP_Hand_API#2]
Hi,

Is there any plan regarding the integration of tactile sensors to the LEAP hand?

Best,

Cem

**Comment by Lucky7Chess** [comment]
HI Cemoke,

I would recommend starting with [Digit](https://digit.ml/) or gelsight touch sensors at the fingertips or [Xela](https://www.xelarobotics.com/) in the fingers.  While, we have not done this yet, it should be straightforward to use and mount.  If you do design 3D printable mounts, feel free to share the CAD mounts with us.

While building in tactile is something that we are interested in and investigating, we have not released our own yet.
