### ISSUE TITLE
Leap Hand cannot move

### ISSUE THREAD

**Issue by AdrianPrados** [leap-hand/LEAP_Hand_API#5]
Good morning, 
we are replicating the LeapHand and have purchased the motors from the pack on your website. We have followed the steps 1 by 1 to use the engines with ROS. Everything launches correctly, but when we send the movement commands the hand does not move. It is not clear how to do it. We have tried entering degrees (20 degrees), we have tried entering radians (0.1 rads) and we have tried entering PWM values (500) and in no case has the hand moved. The connection is correct, since the motor (ID=8) that we are testing turns on and we can see the topcis. Could you tell us how we have to launch the **ros_example.py** and which are the values that we must use to prove that the hand moves?
Best regards and thanks in advance.

**Comment by Lucky7Chess** [comment]
Hi Adrian,

This could be a lot of things which always makes this difficult to debug.  If you go to Dynamixel Studio, can you connect to the motors?  Does all 16 motors show up with different IDs?  Check the serial port of the u2d2 is correct?  

You also need to make sure you have all 16 motors connected if you are using leap hand code as is.  If you only have one motor, ID 8 it will not work.

Also try the Python API and make sure it works at all?  You could have a ros issue and the message isn't coming through as you expect it to.

**Comment by AdrianPrados** [comment]
Yeah, i have been trying only with one motor.
I will try to modify the code to use just one, because we had a problem and 2 of the 16 motors dont turn on.

**Comment by Lucky7Chess** [comment]
If two of the 16 motors don't turn on, you may have two motors with the same ID, or they aren't wired properly.  Or they could be defective but I have not had that issue before.

**Comment by AdrianPrados** [comment]
I think those motors are defective, because the are not detected by Dynamixel Wizard. When we do the scan part, they do not appear in the software and when we connect them to the 5V, the red line does not blink the first time.

**Comment by Lucky7Chess** [comment]
Try another cable?  Try then individually?  Otherwise yeah you must've gotten unlucky.  You can contact Dynamixel support and get replacements.

**Comment by AdrianPrados** [comment]
Yeah we tried different cables and individually and nothing works. 
I have write them to get two others motors. 
Thank you very much @Lucky7Chess

**Comment by Lucky7Chess** [comment]
Got it, unfortunately you must've gotten very unlucky.  Let me know if you have any other issues.
