### ISSUE TITLE
Constant overload flag using Dynamixel motor

### ISSUE THREAD

**Issue by AdrianPrados** [leap-hand/LEAP_Hand_API#6]
Hello again. In the mind time of receiving the replacement motors, we have been testing just one motor using the Dynamixel Wizard 2 software. We have been trying to move with the Packet tool as is presented in this video [https://www.youtube.com/watch?v=cQIDjrfDb24](url). We have the overload problem when trying to move the motor with the finger. We have check your FAQ about the overload problem, and we have change using the Dynamixel Wizard GUI the Current Limit (ID38) and the Goal Current(ID102). We have use the limit of 350mA (as in the code) and we have also used the limit for just one motor (350/16 mA). After changing the value we have the same overload problem.
Is it normal? Have you checked whit just one motor beforehand?

Thanks for your help.

PD: We have try those changes in all motors available.

**Comment by Lucky7Chess** [comment]
Are you using the Leap hand lite?  You may have to use a lower limit than 350...more like 300.  I have found the Lite motors to be not nearly as reliable and consistent.  Also make sure your 5v is steady voltage.

You may also want to try to avoid self-collisions better than just current limiting and do some checking in sim.

**Comment by AdrianPrados** [comment]
Yes, we are using the motors from the Leap Hand lite. We are testing with a single motor, as shown in the Robotis video attached in the previous comment. These tests are being done in a vacuum without using the hand and with the Wizard Dynamixel graphical interface, which we use to send and receive signals. This signal sending shows that the commands are arriving but it is not able to move the motor and enters the overload state.

 As for the issue of auto-collision, it is not possible as we are testing a single engine and there are no collision limits. Also, we are moving it very little to see if the problem was to make sudden movements. We are moving it around 5 and 10 degrees.

We are supplying the voltage with a laboratory power supply while waiting for the power supply you recommend to arrive. The voltage we are working with is 5V but there is a small error of 0.2V, so sometimes we are working with 5.2V. In principle, according to technical specifications, the motors can work between 3.7V and 6V, with 5V being the optimum operating range. However, I don't think that having 0.2V sometimes above the 5V marked as optimal prevents the motors from being commanded.

**Comment by Lucky7Chess** [comment]
You may have a defective motor here.  I'd contact Dynamixel support about it.  I don't make these motors but this seems like a defect.
