### ISSUE TITLE
Recommand/Safe max current for motors

### ISSUE THREAD

**Issue by TheGoblinTechies** [leap-hand/LEAP_Hand_API#7]
Hi,

Thanks for open-sourcing the leaphand. From the python file I noticed that you used 0.35A for the current limit. However, when using this value, it is difficult for me to get accurate joint positions due to the gravity of each finger. From the Dynamixel website for XC330-M288 the motors (https://emanual.robotis.com/docs/en/dxl/x/xc330-m288/), they showed a stall torque 0.93N*m at 5V 1.8A together with a current-torque figure. But they don't show a safe/recommended max current and 1.8A seems quite a large value. During your experience of using this hand, would you know the safe maximum current to get a good control performance while not risking breaking motors? Thanks a lot!

**Comment by Lucky7Chess** [comment]
If you are using the XC motors (not XL) you can raise the current limits as you see fit.  I found 600ma approximately to be a good place.  I made the example conservative so people wouldn't accidentally hurt an XL motor.  Self-collisions cause the most current draw so if you avoid that you may be able to go higher than 600.

**Comment by TheGoblinTechies** [comment]
Thank you! And I am also wondering would you have gravity compensation on the joint control? Since I find there are constantly controlled errors due the weight of the finger even increasing the max current.

**Comment by Lucky7Chess** [comment]
We do not have gravity compensation.  I would recommend raising/tuning the P I and D values to minimize this joint error.
